language: python
python:
  - 2.7
  - 3.4
install:
  - pip install codecov
  - cd Python
  - python setup.py install
  - cd ..
script:
  - cd Python
  - coverage run --source=s_cat setup.py test
after_success:
  - codecov